#!/usr/bin/env bash
# ═══════════════════════════════════════════════════════════════
# Grudge Studio — Legion Node Setup
# Run these steps to register DESKTOP-AA5O5QR as a Coolify
# managed node and connect all machines via ZeroTier.
# ═══════════════════════════════════════════════════════════════
#
# MACHINES:
#   VPS:                74.208.155.229  (production, Coolify host)
#   DESKTOP-AA5O5QR:    10.0.0.217     (local deployer, legion node)
#   GrudgeYonko:        10.0.0.X       (dev machine)
#
# ═══════════════════════════════════════════════════════════════

set -euo pipefail

echo ""
echo "=== PHASE 5: Register DESKTOP-AA5O5QR as Coolify Legion Node ==="
echo ""
echo "── Step 1: SSH into VPS and generate key ──"
echo ""
echo "  ssh root@74.208.155.229"
echo ""
echo "  # On the VPS, generate a dedicated Ed25519 key:"
echo "  ssh-keygen -t ed25519 -a 100 \\"
echo "    -f /data/coolify/ssh/keys/id.root@legion-aa5o5qr \\"
echo '    -q -N "" -C root@coolify-legion'
echo "  chown 9999 /data/coolify/ssh/keys/id.root@legion-aa5o5qr"
echo ""
echo "  # Copy the public key:"
echo "  cat /data/coolify/ssh/keys/id.root@legion-aa5o5qr.pub"
echo ""
echo "── Step 2: On DESKTOP-AA5O5QR, authorize the key ──"
echo ""
echo "  # Open WSL on DESKTOP-AA5O5QR:"
echo "  wsl"
echo ""
echo "  # Ensure SSH is running:"
echo "  sudo apt update && sudo apt install -y openssh-server"
echo "  sudo systemctl enable --now ssh"
echo ""
echo "  # Configure SSH for Coolify:"
echo "  sudo nano /etc/ssh/sshd_config"
echo "  # Ensure these lines are set:"
echo "  #   PubkeyAuthentication yes"
echo "  #   PermitRootLogin prohibit-password"
echo "  sudo systemctl restart ssh"
echo ""
echo "  # Add the public key from Step 1:"
echo "  mkdir -p ~/.ssh"
echo '  echo "<PASTE_PUBLIC_KEY_HERE>" >> ~/.ssh/authorized_keys'
echo "  chmod 700 ~/.ssh"
echo "  chmod 600 ~/.ssh/authorized_keys"
echo ""
echo "── Step 3: Register in Coolify Dashboard ──"
echo ""
echo "  1. Open Coolify: http://74.208.155.229:8000"
echo "  2. Go to Servers → + Add Server"
echo "  3. Enter IP: 10.0.0.217 (or ZeroTier IP after Phase 6)"
echo "     NOTE: For LAN-only access, VPS must reach DESKTOP-AA5O5QR"
echo "     via ZeroTier or port-forward. See Phase 6."
echo "  4. Select the private key: id.root@legion-aa5o5qr"
echo "  5. Click 'Validate Server & Install Docker Engine'"
echo "  6. Wait for: Proxy Running ✅"
echo ""
echo "── Step 4: Deploy game server to legion node ──"
echo ""
echo "  # In Coolify, create a new application or move grudge-headless"
echo "  # to the legion node server. The headless server uses:"
echo "  #   - Port 7777 (TCP + UDP) for game traffic"
echo "  #   - MySQL connection via ZeroTier private IP"
echo "  #   - Up to 22 players (MAX_PLAYERS env var)"
echo ""
echo ""
echo "=== PHASE 6: ZeroTier Private Network ==="
echo ""
echo "── Step 1: Create a ZeroTier network ──"
echo ""
echo "  1. Go to: https://my.zerotier.com/network"
echo "  2. Click 'Create A Network'"
echo "  3. Name it: grudge-studio-mesh"
echo "  4. Set Access Control to 'Private' (members must be authorized)"
echo "  5. Copy the Network ID (e.g., a1b2c3d4e5f6g7h8)"
echo ""
echo "── Step 2: Join GrudgeYonko (this machine) ──"
echo ""
echo "  # In PowerShell (admin) on GrudgeYonko:"
echo '  zerotier-cli join <NETWORK_ID>'
echo ""
echo "  # Then authorize in the ZeroTier dashboard"
echo "  # Assign a memorable IP like 10.147.17.1"
echo ""
echo "── Step 3: Join DESKTOP-AA5O5QR ──"
echo ""
echo "  # In PowerShell (admin) on DESKTOP-AA5O5QR:"
echo '  zerotier-cli join <NETWORK_ID>'
echo ""
echo "  # Authorize in dashboard, assign IP like 10.147.17.2"
echo ""
echo "── Step 4: Join VPS ──"
echo ""
echo "  # SSH into VPS:"
echo "  ssh root@74.208.155.229"
echo ""
echo "  # Install ZeroTier:"
echo "  curl -s https://install.zerotier.com | bash"
echo '  zerotier-cli join <NETWORK_ID>'
echo ""
echo "  # Authorize in dashboard, assign IP like 10.147.17.10"
echo ""
echo "── Step 5: Test connectivity ──"
echo ""
echo "  # From GrudgeYonko:"
echo "  ping 10.147.17.2    # DESKTOP-AA5O5QR"
echo "  ping 10.147.17.10   # VPS"
echo ""
echo "  # From VPS:"
echo "  ping 10.147.17.2    # DESKTOP-AA5O5QR"
echo "  curl http://10.147.17.2:3003/health  # game-api on legion node"
echo ""
echo "── Step 6: Update Coolify server IP ──"
echo ""
echo "  # In Coolify dashboard, update the legion node server IP"
echo "  # from 10.0.0.217 → 10.147.17.2 (ZeroTier IP)"
echo "  # This ensures stable connectivity even if LAN IPs change"
echo ""
echo ""
echo "=== ZeroTier Benefits ==="
echo ""
echo "  ✅ Stable IPs — no more LAN IP changes breaking things"
echo "  ✅ VPS can reach DESKTOP-AA5O5QR — enables Coolify management"
echo "  ✅ Encrypted mesh — all traffic between machines is encrypted"
echo "  ✅ Hybrid deployment — run game servers locally, connect to prod DB"
echo "  ✅ Works from anywhere — VPN-like access even outside home network"
echo ""
echo "=== All Phases Complete ==="
echo ""
