#!/bin/bash
# ─────────────────────────────────────────────────────────────────
# Grudge Studio — VPS Full Bootstrap Script (non-interactive)
# Usage:
#   bash <(curl -fsSL https://TOKEN@raw.githubusercontent.com/MolochDaGod/grudge-studio-backend/main/scripts/setup-vps.sh)
# ─────────────────────────────────────────────────────────────────
set -e

GREEN='\033[0;32m'; YELLOW='\033[1;33m'; RED='\033[0;31m'; CYAN='\033[0;36m'; NC='\033[0m'
log()  { echo -e "${GREEN}✓${NC} $1"; }
warn() { echo -e "${YELLOW}▶${NC} $1"; }
err()  { echo -e "${RED}✗${NC} $1"; }

DEPLOY_DIR="/opt/grudge-studio-backend"
GH_TOKEN="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"
REPO_URL="https://${GH_TOKEN}@github.com/MolochDaGod/grudge-studio-backend.git"

echo -e "${CYAN}"
echo "  ╔══════════════════════════════════════════╗"
echo "  ║   GRUDGE STUDIO — VPS BOOTSTRAP          ║"
echo "  ╚══════════════════════════════════════════╝"
echo -e "${NC}"

# ── 1. System update ──────────────────────────────────────────────
warn "[1/8] Updating system..."
export DEBIAN_FRONTEND=noninteractive
apt-get update -qq
apt-get install -y -qq curl git ufw nano rsync jq ca-certificates gnupg lsb-release
log "System packages ready"

# ── 2. Install Docker ─────────────────────────────────────────────
warn "[2/8] Installing Docker..."
if ! command -v docker &>/dev/null; then
  curl -fsSL https://get.docker.com | sh
  systemctl enable docker && systemctl start docker
fi
log "Docker: $(docker --version)"

if ! docker compose version &>/dev/null 2>&1; then
  apt-get install -y -qq docker-compose-plugin
fi
log "Docker Compose: $(docker compose version --short 2>/dev/null || docker compose version)"

# ── 3. Firewall ───────────────────────────────────────────────────
warn "[3/8] Configuring firewall..."
ufw --force enable
ufw allow OpenSSH
ufw allow 80/tcp
ufw allow 443/tcp
ufw allow 7777/tcp
ufw allow 7777/udp
log "Firewall configured (SSH + 80/443 + 7777 open)"

# ── 4. Clone / update repo ────────────────────────────────────────
warn "[4/8] Setting up repo at $DEPLOY_DIR..."
if [ -d "$DEPLOY_DIR/.git" ]; then
  warn "  Repo exists — pulling latest..."
  cd "$DEPLOY_DIR"
  git remote set-url origin "$REPO_URL"
  git fetch origin
  git reset --hard origin/main
else
  mkdir -p "$DEPLOY_DIR"
  git clone "$REPO_URL" "$DEPLOY_DIR"
fi
cd "$DEPLOY_DIR"
log "Repo ready at commit $(git rev-parse --short HEAD)"

# ── 5. Install Node.js ────────────────────────────────────────────
warn "[5/8] Checking Node.js..."
if ! command -v node &>/dev/null; then
  curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
  apt-get install -y -qq nodejs
fi
log "Node.js $(node -v)"

# ── 6. Create .env ────────────────────────────────────────────────
warn "[6/8] Setting up .env..."
cd "$DEPLOY_DIR"
if [ -f ".env" ]; then
  log ".env already exists — keeping it"
else
  warn "  Generating .env with secure random secrets..."
  node scripts/gen-secrets.js > .env
  # Patch production values
  sed -i 's|NODE_ENV=development|NODE_ENV=production|g' .env
  # Append required vars not generated by gen-secrets
  cat >> .env << 'ENVEOF'

# ── AUTH SERVICES (fill these in) ──────────────────────────────
DISCORD_CLIENT_ID=REPLACE_ME
DISCORD_CLIENT_SECRET=REPLACE_ME
DISCORD_REDIRECT_URI=https://id.grudge-studio.com/auth/discord/callback
WEB3AUTH_CLIENT_ID=REPLACE_ME
WALLET_MASTER_SEED=REPLACE_ME_24_WORD_MNEMONIC
SOLANA_RPC_URL=https://api.mainnet-beta.solana.com

# ── CLOUDFLARE R2 STORAGE ───────────────────────────────────────
OBJECT_STORAGE_ENDPOINT=REPLACE_ME
OBJECT_STORAGE_BUCKET=grudge-studio-assets
OBJECT_STORAGE_KEY=REPLACE_ME
OBJECT_STORAGE_SECRET=REPLACE_ME
OBJECT_STORAGE_REGION=auto
OBJECT_STORAGE_PUBLIC_URL=https://assets.grudge-studio.com

# ── CORS / DOMAINS ──────────────────────────────────────────────
CORS_ORIGINS=https://grudgewarlords.com,https://grudge-studio.com,https://grudgestudio.com,https://grudachain.grudge-studio.com,https://dash.grudge-studio.com,https://app.puter.com
MAX_PLAYERS=22
ENVEOF
  log ".env generated (crypto secrets are randomised, fill in REPLACE_ME values later)"
  echo ""
  warn "  NOTE: Services will start but Discord/Web3Auth/Solana won't work until"
  warn "  you fill in the REPLACE_ME values:  nano $DEPLOY_DIR/.env"
fi

# Sanity check required vars
MISSING=0
for VAR in MYSQL_ROOT_PASSWORD MYSQL_DATABASE MYSQL_USER MYSQL_PASSWORD JWT_SECRET INTERNAL_API_KEY REDIS_PASSWORD; do
  grep -q "^${VAR}=" .env 2>/dev/null || { err "Missing: $VAR"; MISSING=$((MISSING+1)); }
done
[ $MISSING -gt 0 ] && { err "$MISSING required vars missing from .env"; exit 1; }
log "Required env vars present"

# ── 7. Generate SSH deploy key for GitHub Actions ─────────────────
warn "[7/8] Setting up GitHub Actions SSH deploy key..."
KEY_FILE="$HOME/.ssh/grudge_deploy"
mkdir -p ~/.ssh && chmod 700 ~/.ssh
if [ ! -f "$KEY_FILE" ]; then
  ssh-keygen -t ed25519 -C "grudge-deploy@$(hostname -I | awk '{print $1}')" -f "$KEY_FILE" -N ""
  cat "${KEY_FILE}.pub" >> ~/.ssh/authorized_keys
  chmod 600 ~/.ssh/authorized_keys
  log "SSH deploy key generated"
else
  log "SSH deploy key already exists"
fi

# Auto-push secrets to GitHub Actions if gh CLI is available
if command -v gh &>/dev/null 2>&1; then
  warn "  Pushing secrets to GitHub Actions via gh CLI..."
  VPS_IP=$(hostname -I | awk '{print $1}')
  REPO="MolochDaGod/grudge-studio-backend"
  gh secret set DEPLOY_SSH_KEY    --repo "$REPO" --body "$(cat $KEY_FILE)"
  gh secret set VPS_HOST          --repo "$REPO" --body "$VPS_IP"
  gh secret set VPS_USER          --repo "$REPO" --body "$(whoami)"
  gh secret set VPS_PASSWORD      --repo "$REPO" --body "Hf8vBjMC"
  log "GitHub Actions secrets pushed!"
else
  warn "  gh CLI not found — copy the key below manually"
fi

echo ""
echo -e "${CYAN}  ┌─────────────────────────────────────────────────────────────┐${NC}"
echo -e "${CYAN}  │  DEPLOY_SSH_KEY — add to GitHub → Settings → Secrets       │${NC}"
echo -e "${CYAN}  └─────────────────────────────────────────────────────────────┘${NC}"
cat "$KEY_FILE"
echo ""

# ── 8. Build and start all services ───────────────────────────────
warn "[8/8] Building and starting all services..."
cd "$DEPLOY_DIR"

# Start Traefik + infrastructure first
docker compose up -d traefik mysql redis
warn "  Waiting for MySQL to be healthy..."
for i in $(seq 1 30); do
  docker compose exec -T mysql mysqladmin ping -h localhost --silent 2>/dev/null && break
  sleep 2
done
log "MySQL healthy"
log "Traefik started (TLS certs will provision on first HTTPS request)"

# Build all app services
warn "  Building services (takes a few minutes first time)..."
DOCKER_BUILDKIT=1 docker compose build \
  --build-arg BUILDKIT_INLINE_CACHE=1 \
  grudge-id wallet-service game-api ai-agent account-api launcher-api asset-service ws-service

# Start app services
docker compose up -d --no-deps \
  grudge-id wallet-service game-api ai-agent account-api launcher-api asset-service ws-service

log "All services started"

# ── Run migrations ─────────────────────────────────────────────────
warn "  Running SQL migrations..."
bash scripts/migrate.sh && log "Migrations complete" || warn "Migration script not found — skipping"

# ── Health checks ──────────────────────────────────────────────────
warn "  Running health checks (waiting 15s for startup)..."
sleep 15
FAIL=0
for SVC_PORT in "grudge-id:3001" "game-api:3003" "ai-agent:3004" "account-api:3005" "launcher-api:3006" "ws-service:3007" "asset-service:3008"; do
  SVC="${SVC_PORT%%:*}"; PORT="${SVC_PORT##*:}"
  if curl -sf "http://localhost:$PORT/health" >/dev/null 2>&1; then
    echo -e "  ${GREEN}✅ $SVC (port $PORT)${NC}"
  else
    echo -e "  ${RED}❌ $SVC (port $PORT) — docker logs $SVC --tail 20${NC}"
    FAIL=$((FAIL+1))
  fi
done

docker compose ps

echo ""
VPS_IP=$(hostname -I | awk '{print $1}')
if [ $FAIL -eq 0 ]; then
  echo -e "${GREEN}"
  echo "  ╔══════════════════════════════════════════════════════════════╗"
  echo "  ║   🎉  GRUDGE STUDIO BACKEND — PRODUCTION LIVE!             ║"
  echo "  ╠══════════════════════════════════════════════════════════════╣"
  echo "  ║  VPS IP:  $VPS_IP                                   ║"
  echo "  ║  Traefik: https://traefik.grudge-studio.com (TLS auto)     ║"
  echo "  ║  Status:  https://status.grudge-studio.com                  ║"
  echo "  ║  Repo:    /opt/grudge-studio-backend/                       ║"
  echo "  ║  Logs:    docker compose logs -f                            ║"
  echo "  ╠══════════════════════════════════════════════════════════════╣"
  echo "  ║  Service Endpoints (behind Traefik TLS):                    ║"
  echo "  ║  • https://id.grudge-studio.com       (grudge-id:3001)     ║"
  echo "  ║  • https://api.grudge-studio.com      (game-api:3003)      ║"
  echo "  ║  • https://account.grudge-studio.com  (account-api:3005)   ║"
  echo "  ║  • https://launcher.grudge-studio.com (launcher-api:3006)  ║"
  echo "  ║  • https://ws.grudge-studio.com       (ws-service:3007)    ║"
  echo "  ║  • https://assets-api.grudge-studio.com (asset-service)    ║"
  echo "  ╠══════════════════════════════════════════════════════════════╣"
  echo "  ║  ⚠  DNS — point these A records to $VPS_IP:       ║"
  echo "  ║     id, api, account, launcher, ws, assets-api,            ║"
  echo "  ║     status, traefik  → ALL to $VPS_IP              ║"
  echo "  ╠══════════════════════════════════════════════════════════════╣"
  echo "  ║  ⚠  Still fill in .env REPLACE_ME values:                  ║"
  echo "  ║     nano /opt/grudge-studio-backend/.env                    ║"
  echo "  ║     (Discord, Web3Auth, Solana, R2 storage keys)           ║"
  echo "  ╚══════════════════════════════════════════════════════════════╝"
  echo -e "${NC}"
else
  echo -e "${YELLOW}Deploy complete — $FAIL service(s) need attention.${NC}"
  echo "  Check logs: docker compose logs <service-name> --tail 50"
  echo "  Common fixes:"
  echo "    docker compose logs grudge-id --tail 30"
  echo "    docker compose restart grudge-id"
fi
