const router = require('express').Router();
const { getDB } = require('../db');
const { requireAuth } = require('../middleware/auth');

const MAX_COMPUTERS = 5;

// ── POST /register-computer ───────────────────────────────────────
// Auth required — register or refresh a machine with the Grudge Launcher.
// On first registration the 'launcher_install' achievement is awarded.
// Body: {
//   computer_id,        — stable UUID generated by launcher and persisted on disk
//   fingerprint_hash?,  — SHA-256(mac+drive+cpu) for extra binding
//   platform?,          — 'windows' | 'mac' | 'linux'
//   launcher_version?,  — e.g. "1.0.0"
//   label?              — user-friendly name e.g. "Gaming PC"
// }
router.post('/register-computer', requireAuth, async (req, res, next) => {
  const me = req.user.grudge_id;
  const { computer_id, fingerprint_hash = null, platform = null,
          launcher_version = null, label = null } = req.body;

  if (!computer_id) return res.status(400).json({ error: 'computer_id is required' });

  const db = getDB();
  try {
    // Check if this computer is already registered (any owner)
    const [[existing]] = await db.query(
      'SELECT id, grudge_id, is_revoked FROM computer_registrations WHERE computer_id = ?',
      [computer_id]
    );

    if (existing) {
      // If revoked by owner, reject
      if (existing.grudge_id === me && existing.is_revoked) {
        return res.status(403).json({ error: 'This computer has been revoked. Contact support.' });
      }
      // Refresh last_seen and version
      await db.query(
        `UPDATE computer_registrations
         SET last_seen = CURRENT_TIMESTAMP,
             launcher_version = COALESCE(?, launcher_version),
             label = COALESCE(?, label)
         WHERE computer_id = ? AND grudge_id = ?`,
        [launcher_version, label, computer_id, me]
      );
      return res.json({ computer_id, registered: false, refreshed: true });
    }

    // New registration — enforce cap
    const [[{ count }]] = await db.query(
      'SELECT COUNT(*) AS count FROM computer_registrations WHERE grudge_id = ? AND is_revoked = FALSE',
      [me]
    );
    if (count >= MAX_COMPUTERS) {
      return res.status(409).json({
        error: `Maximum of ${MAX_COMPUTERS} computers allowed. Revoke one from your account settings.`,
      });
    }

    await db.query(
      `INSERT INTO computer_registrations
         (grudge_id, computer_id, fingerprint_hash, platform, launcher_version, label)
       VALUES (?, ?, ?, ?, ?, ?)`,
      [me, computer_id, fingerprint_hash, platform, launcher_version, label]
    );

    // Award achievement (idempotent)
    await db.query(
      'INSERT IGNORE INTO user_achievements (grudge_id, achievement_key) VALUES (?, ?)',
      [me, 'launcher_install']
    ).catch(() => {/* best-effort */});

    res.status(201).json({ computer_id, registered: true });
  } catch (err) {
    next(err);
  }
});

module.exports = router;
